apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-7li7
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/cin4s-839-0043-tenant/cin4s-839-0043-app/devfile-sample-7li7@sha256:c90ecbe9898688f6b4219bb9b523d91c7ddcf32ab364303ebfa1d3555d37db02
        name: my-nodejs
        resources: {}
status: {}
